language: python
fast_finish: true

python:
  - 2.7
  - 3.6
  - 3.7-dev

os:
  - linux

group: travis_latest

git:
  depth: 3


install: pip install -e .

script: pytest -v

after_success: 
  - coverage run tests/test_all.py
  - coveralls

