name: ci

on:
  push:
    paths:
    - "**/*.py"
    - .github/workflows/ci.yml


jobs:

  full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.x]

    steps:
    - uses: actions/checkout@v4

    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
